services:

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_storage:/qdrant/storage

  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    environment:
      OLLAMA_CONTEXT_LENGTH: 8192
      # OLLAMA_DEBUG: 2
    healthcheck:
      test:  [ "CMD-SHELL", "bash", "-c", "{ printf >&3 'GET / HTTP/1.0\\r\\n\\r\\n'; cat <&3; } 3<>/dev/tcp/localhost/11434 | grep 'Ollama is' || exit 1"  ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  ammrag:
    build: .
    container_name: ammrag
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8001:8001"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: supersecret
      QDRANT_URL: http://qdrant:6333
      OLLAMA_HOST: http://ollama:11434
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
    networks:
      mynet:
        aliases:
          - ammrag
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  fileshare:
    build: utils/fileshare/.
    ports:
      - "8642:8642"
    volumes:
      - ./data/mmore/input:/app/pub:ro
    restart: unless-stopped
    networks:
      mynet:
        aliases:
          - fileserve

      
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: supersecret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
    ollama:    
    postgres_data:

networks:
  mynet:
    external: true