indexer:
  dense_model:
    model_name: sentence-transformers/all-MiniLM-L6-v2
    is_multimodal: false
  sparse_model:
    model_name: splade
    is_multimodal: false
  db:
    uri: /data/vectors/nss.db
    name: nss
collection_name: nss
documents_path: '/workspaces/mmore_qdrant/data/results/merged/merged_results.jsonl'
